selenium-hub:
  image: selenium/hub
  ports:
  - 4444:4444

chrome:
  image: selenium/node-chrome
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

#firefox:
#  image: selenium/node-firefox
#  environment:
#    HUB_PORT_4444_TCP_ADDR: hub
#  links:
#  - selenium-hub:hub

fiware_report: 
  image: mongo
  volumes: 
    - ./ge_fiware/report:/data/db
  ports: 
    - 27017:27017
  command: bash -c "mongoimport --db report_fiware --collection fiware --file report.json"
